services:
  db:
    image: postgres:15-alpine
    container_name: task-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: task-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/taskdb?schema=public"
      NODE_ENV: development
      JWT_SECRET: change-this-to-something-long-and-random-later
    depends_on:
      - db
    volumes:
      - .:/app
    command: >-
      sh -c "until npx prisma migrate dev --name init; do
             echo 'Waiting for database to be ready...';
             sleep 2;
           done &&
           node server.js"
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - api
volumes:
  postgres_data:
